global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gatewayapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['gatewayapi:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
